- name: MySQL Backup directory
  file:
    path: /home/backup/mysql
    state: directory
    owner: backup
    
- name: MySQL Backup restore directory
  file:
    path: /home/backup/restore/mysql
    state: directory
    owner: backup    
       

- name: Create MySQL user "backup" 
  community.mysql.mysql_user:
    name: backup
    password: "{{ backup_pass }}"
    priv: "{{ mysql_database }}.*:LOCK TABLES,SELECT"
    host: "%"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true
  when: inventory_hostname=="sikiteeb-2"

- name: .my.cnf file  
  template:
    src: .my.cnf.j2
    dest: /home/backup/.my.cnf
    owner: backup
    mode: '0400'
  no_log: true
  when: inventory_hostname == "sikiteeb-2"
    
- name: MySQL backup cron
  template:
    src: mysql-backup.j2
    dest: /etc/cron.d/mysql-backup
    owner: root
    mode: 0750

- name: Enable Cron
  service:
    name: cron
    state: started
    enabled: true

