- name: Install Nginx
  apt:
    name: nginx

- name: Place index.html
  copy:
    src: index.html
    dest: /var/www/html/index.html

- name: Copy default.j2
  copy:
    src: default
    dest: /etc/nginx/sites-enabled/default
  notify:
    - Restart Nginx

- name: Enable Nginx
  service:
    name: nginx
    state: started
    enabled: true