- name: Install Nginx
  apt:
    name: nginx

- name: Default file
  template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify:
    - Restart Nginx

- name: Enable Nginx
  service:
    name: nginx
    state: started
    enabled: true