- name: Install Nginx
  apt:
    name: nginx

- name: Default file
  template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify:
    - Restart Nginx
    
- name: Expose stub_status on Port 8080
  template:
    src: stub_status
    dest: /etc/nginx/sites-enabled/stub_status
  notify:
    - Restart Nginx Exporter
    - Restart Nginx
    - Reload Daemons

- name: Enable Nginx
  service:
    name: nginx
    state: started
    enabled: true