- name: Create Grafana directory
  file: 
    path: "{{ item }}"
    state: directory
    recurse: true
  loop:
      - /opt/grafana/provisioning/dashboards
      - /opt/grafana/provisioning/datasources

- name: Grafana Init Config
  template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini
  notify: Restart Grafana Docker
  no_log: true

- name: Grafana Dashboard Setting
  template:
    src: dashboard.yaml.j2
    dest: /opt/grafana/provisioning/dashboards/default.yaml
  notify: Restart Grafana Docker

- name: Grafana Datasource Setting
  template:
    src: datasource.yaml.j2
    dest: /opt/grafana/provisioning/datasources/default.yaml
  notify: Restart Grafana Docker

- name: Create Grafana Dashboards Json Folder
  file:
    path: /opt/grafana/provisioning/dashboard-jsons
    state: directory

- name: Main Dashboard Json
  copy:
    src: "../files/{{ item }}"
    dest: /opt/grafana/provisioning/dashboard-jsons/{{ item }}
    recurse: no
  loop:
    - main.json 
    - mysql.json
    - syslog.json
  notify: Restart Grafana Docker
  
- name: Grafana Docker 
  community.docker.docker_container:
   name: grafana
   image: grafana/grafana:9.2.6
   published_ports: "{{ grafana_port }}:3000"
   volumes: /opt/grafana:/etc/grafana
   restart_policy: always
   dns_search_domains: "{{ domain }}"
   dns_servers: 
    - "{{ hostvars[groups['dns_secondary'][0]]['ansible_default_ipv4']['address'] }}"
 #  - "{{ hostvars[groups['dns_secondary'][1]]['ansible_default_ipv4']['address'] }}"