- name: Create Grafana directory
  file: 
    path: "{{ item }}"
    state: directory
    recurse: yes
  loop:
      - /opt/grafana/provisioning/dashboards
      - /opt/grafana/provisioning/datasources

- name: Grafana Init Config
  template:
    src: grafana.ini.j2
    dest: /opt/grafana/grafana.ini
  notify: Restart Grafana
  no_log: true

- name: Grafana Dashboard Setting
  template:
    src: dashboard.yaml.j2
    dest: /opt/grafana/provisioning/dashboards/default.yaml
  notify: Restart Grafana

- name: Grafana Datasource Setting
  template:
    src: datasource.yaml.j2
    dest: /opt/grafana/provisioning/datasources/default.yaml
  notify: Restart Grafana

- name: Create Grafana Dashboards Json Folder
  file:
    path: /opt/grafana/provisioning/dashboard-jsons
    state: directory

- name: Main Dashboard Json
  copy:
    src: "../files/{{ item }}"
    dest: /opt/grafana/provisioning/dashboard-jsons/{{ item }}
  loop:
    - main.json 
    - bind.json
    - nginx.json
  notify: Restart Grafana 
  
