
- name: Download Grafana
  get_url:
    url: https://dl.grafana.com/oss/release/grafana_7.2.1_amd64.deb
    dest: /opt/grafana_7.2.1_amd64.deb

- name: Install Grafana
  apt:
    deb: /opt/grafana_7.2.1_amd64.deb

- name: Grafana Init Config
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify: Restart Grafana

- name: Grafana Dashboard Setting
  template:
    src: dashboard.yaml.j2
    dest: /etc/grafana/provisioning/dashboards/dashboard.yaml
  notify: Restart Grafana

- name: Grafana Datasource Setting
  template:
    src: datasource.yaml.j2
    dest: /etc/grafana/provisioning/datasources/default.yaml
  notify: Restart Grafana

- name: Create Grafana Dashboards Json Folder
  file:
    path: /etc/grafana/provisioning/dashboard-jsons
    state: directory
    group: grafana

- name: Enable Grafana
  service:
    name: grafana-server
    state: started
    enabled: true
  