---
- name: Set up
  hosts: all
  become: true
  gather_facts: true
  roles:
    - init
  
- name: Bind
  hosts: dns_servers
  become: true
  gather_facts: false
  roles:
    - bind
    - bind_exporter
  tags:
    - dns
    
- name: Database server
  hosts: db_servers
  become: true
  gather_facts: false
  roles:
    - mysql
    - mysql_exporter
  tags:
    - db
  
- name: Web server
  hosts: web_servers
  become: true
  gather_facts: false
  roles:
    - agama
    - uwsgi
    - nginx
  tags: 
    - web

- name: Nginx
  hosts: all
  become: yes
  gather_facts: false
  roles:
   - nginx
   - nginx_exporter
  tags:
    - ng

- name: Prometheus
  hosts: prometheus
  become: true
  gather_facts: false
  roles:
    - prometheus
    - node_exporter
  tags: 
    - pro      
      
- name: Grafana
  hosts: grafana
  become: yes
  gather_facts: false
  roles:
    - grafana
  tags: gr     



  