---
- name: Set up
  hosts: all
  become: true
  gather_facts: true
  roles:
    - init
  
- name: Web server
  hosts: web_servers
  become: true
  gather_facts: false
  roles:
    - agama
    - uwsgi
    - nginx
    
    
  tags: web
  