---

- name: Setup
  hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - setup:
  
- name: Global
  hosts: all
  become: yes
  gather_facts: no
  roles:      
    - init
    - node_exporter
    - rsyslog
    - docker
      
- name: Backup
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - backup
  tags: ba      
 

- name: DNS
  hosts: dns_servers
  become: yes
  gather_facts: no
  roles:
    - bind
    - bind_exporter
  tags:
    - dns
 
- name: Database server
  hosts: db_servers
  become: yes
  gather_facts: no
  roles:
    - mysql
    - mysql_exporter
    - mysql_backup
  tags: 
    - db
    
- name: Web server
  hosts: web_servers
  become: yes
  gather_facts: no
  roles:
    - agama
  tags: 
    - aga
      
- name: Keepalived and Haproxy
  hosts: haproxy
  become: yes
  gather_facts: no
  roles:
    - keepalived
    - haproxy
  tags:
    - ha

- name: Nginx
  hosts: all
  become: yes
  gather_facts: no
  roles:
   - nginx
   - nginx_exporter
  tags:
    - ng
      
- name: Influxdb
  hosts: influxdb  
  become: yes
  gather_facts: no 
  roles:
    - influxdb 
    - pinger
    - influxdb_exporter
    - influxdb_backup
  tags: in

- name: Prometheus
  hosts: prometheus
  become: yes
  gather_facts: no
  roles:
    - prometheus
  tags: pro


- name: Grafana 
  hosts: grafana
  become: yes
  gather_facts: no
  roles:
    - grafana
  tags: gr