---

- name: Setup
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - setup:
  
- name: Global
  hosts: all
  become: true
  gather_facts: false
  roles:      
    - init
    - node_exporter
    - rsyslog
      
- name: Backup
  hosts: all
  become: true
  gather_facts: false
  roles:
    - backup
  tags: ba      
 

- name: DNS
  hosts: dns_servers
  become: true
  gather_facts: false
  roles:
    - bind
    - bind_exporter
  tags:
    - dns
 
- name: Database server
  hosts: db_servers
  become: true
  gather_facts: false
  roles:
    - mysql
    - mysql_exporter
    - mysql_backup
  tags: 
    - db
    
- name: Web server
  hosts: web_servers
  become: true
  gather_facts: false
  roles:
    - agama
    - uwsgi
    - nginx
  tags: 
    - web

- name: Nginx
  hosts: all
  become: true
  gather_facts: false
  roles:
   - nginx
   - nginx_exporter
  tags:
    - ng
      
- name: Influxdb
  hosts: influxdb  
  become: true
  gather_facts: false 
  roles:
    - influxdb 
    - pinger
    - influxdb_exporter
  tags: in

- name: Prometheus
  hosts: prometheus
  become: true
  gather_facts: false
  roles:
    - prometheus
  tags: pro


- name: Grafana 
  hosts: grafana
  become: true
  gather_facts: true
  roles:
    - grafana
  tags: gr