- name: Create directory Agama
  file:
    path: /opt/agama
    state: directory
  
- name: Install Agama 
  get_url:
    url: "{{ item }}"
    dest: /opt/agama
  loop:
    - https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    - https://raw.githubusercontent.com/hudolejev/agama/master/Dockerfile

- name: Build Agama docker image
  community.docker.docker_image: 
    name: agama 
    source: build 
    build:
      path: /opt/agama
    
- name: Agama Docker containers:"{{ agama_containers }}"
  community.docker.docker_container:
    name: "agama{{ item }}"
    image: agama
    restart_policy: always
    state: started
    published_ports: "{{ agama_port + item | int }}:8000"
    container_default_behavior: no_defaults
    env:
      AGAMA_DATABASE_URI: mysql+pymysql://{{mysql_user}}:{{mysql_password}}@{{mysql_host}}/{{mysql_database}}
  with_sequence: count={{ agama_containers }}
    
    
  