- name: Create User "backup"
  user:
    name: backup
    group: backup
    home: /home/backup
    shell: /bin/bash
    generate_ssh_key: yes
    
- name: Known_hosts key file
  template:
    src: known_hosts.j2
    dest: /home/backup/.ssh/known_hosts
    group: backup
    owner:  backup
    mode: 0774
  no_log: true
  
- name: Install Duplicity
  apt:
    name: duplicity 
    state: latest
