- name: Create User "backup"
  user:
    name: "{{ backup_user }}"
    group: "{{ backup_user }}"
    home: /home/backup
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    
- name: known_hosts file
  template:
    src: known_hosts.j2
    dest: /home/backup/.ssh/known_hosts
    group: "{{ backup_user }}"
    owner: "{{ backup_user }}"
    mode: 0770
  no_log: false
  
- name: Add backup to mysql group on sikiteeb-2
  user:
    name: backup
    groups: mysql
  when: inventory_hostname == "sikiteeb-2" 

- name: Create backup, restore and scripts directories
  file:
    path: /home/backup/{{ item }}
    state: directory
    owner: backup
    group: backup
    mode: '0755'
  loop:
    - backup
    - restore

- name: Install Duplicity
  apt:
    name: duplicity 
    state: latest
