- name: InfluxDB Backup directory
  file:
    path: /home/backup/influxdb
    state: directory
    owner: "{{ backup_user }}"

- name: InfluxDB cron
  template: 
    src: influxdb-backup.j2
    dest: /etc/cron.d/influxdb-backup
    owner: root
    mode: '0744'

- name: Enable Cron
  service:
    name: cron
    state: started
    enabled: true