- name: Install Node Exporter
  apt:
    name: prometheus-node-exporter

- name: Node Exporter arg
  template:
    src: prometheus-node-exporter
    dest: /etc/default/prometheus-node-exporter
  notify: Restart Node Exporter

- name: Enable Node exporter
  service:
    name: prometheus-node-exporter
    state: started
    enabled: true