- name: Install Nginx Exporter
  apt:
    name: prometheus-nginx-exporter
    
- name: Nginx-exporter args
  template:
    src: prometheus-nginx-exporter
    dest: /etc/default/prometheus-nginx-exporter
  notify:
    - Restart Nginx Exporter

- name: Enable Nginx Exporter
  service:
    name: prometheus-nginx-exporter
    state: started
    enabled: true