- name: Install Bind9 
  apt:
    name:
      - bind9
      - bind9utils
      - bind9-doc 
      - dnsutils
      
- name: Options conf
  template:
    src: named.conf.options
    dest: /etc/bind/named.conf.options
  notify:
    - Restart Bind9
    - Reload rndc
    
- name: Local conf
  template: 
    src: named.conf.local
    dest: /etc/bind/named.conf.local
  notify:
    - Restart Bind9
    - Reload rndc  

- name: DNS primary Zone
  template:
    src: db.maledetta
    dest: /var/cache/bind/db.maledetta
    force: no
  notify:
    - Restart Bind9
    - Reload rndc
  when: inventory_hostname in groups ['dns_primary']
    
    
- name: Forward lookup zone file
  template:
    src: forward.maledetta.local
    dest: /etc/bind/
  notify:
    - Restart Bind9
    - Reload rndc  
    
- name: Reverse lookup zone file
  template:
    src: reverse.maledetta.local
    dest: /etc/bind/reverse.maledetta.local
  notify:
    - Restart Bind9
    - Reload rndc  
       
- name: Enable bind9
  service:
    name: bind9
    state: started
    enabled: true
      
      
        