- name: Install bind9
  apt:
    name: 
      - bind9
      - python3-dnspython
  
- name: Option
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  no_log: True
  notify: 
    - Restart Bind9
    - Reconfigure rndc
  

- name: Local  
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify: 
    - Restart Bind9
    - Reconfigure rndc
  
  
- name: DNS Primary Zone
  template: 
    src: db.maledetta.j2
    dest: /var/cache/bind/db.domain
    force: no
  notify: 
    - Restart Bind9
    - Reconfigure rndc
  when: inventory_hostname in groups ['dns_master']
  

- name: Reverse DNS Primary Zone
  template: 
    src: db.reverse.j2
    dest: /var/cache/bind/db.domain.reverse
    force: no
  notify: 
    - Restart Bind9
    - Reconfigure rndc
  when: inventory_hostname in groups ['dns_master']
  

- name: Enable bind9
  service:
    name: bind9
    state: started
    enabled: yes

- name: execute handlers
  meta: flush_handlers

- name: Wait for 15 sec
  pause:
    seconds: 15
  when: dns_config.changed

- name: Create A records
  community.general.nsupdate:
    key_name: "nsupdate.key"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ nsupdate_key }}"
    server: "localhost"
    zone: "{{ fqdn }}"
    record: "{{ item.key }}"
    type: "A"
    value: "{{ item.value }}"
  loop: "{{ dns_a_records | dict2items }}"
  run_once: True
  when: inventory_hostname in groups ['dns_master']

- name: Create CNAME records
  community.general.nsupdate:
    key_name: "nsupdate.key"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ nsupdate_key }}"
    server: "localhost"
    zone: "{{ fqdn }}"
    record: "{{ item.key }}"
    type: "CNAME"
    value: "{{ item.value }}"
  loop: "{{ dns_cname_records | dict2items }}"
  run_once: True
  when: inventory_hostname in groups ['dns_master']