- name: Install Bind9 
  apt:
    name:
      - bind9
      - bind9utils
      - bind9-doc 
      - dnsutils
        
- name: Resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf

- name: Stop systemd-resolved
  systemd:
    name: systemd-resolved
    enabled: no
    state: stopped        
     
- name: Options conf
  template:
    src: named.conf.options
    dest: /etc/bind/named.conf.options
  notify:
    - Restart Bind9
    - Reconfigure rndc
    
- name: Local conf
  template: 
    src: named.conf.local
    dest: /etc/bind/named.conf.local
  notify:
    - Restart Bind9
    - Reconfigure rndc  
       
- name: DNS primary Zone
  template:
    src: db.maledetta
    dest: /var/cache/bind/db.maledetta
    force: no
  notify:
    - Restart Bind9
    - Reconfigure rndc
  when: inventory_hostname in groups ['dns_primary']
     
- name: Reverse lookup zone file
  template:
    src: db.maledetta.reverse
    dest: /var/cache/bind/db.maledetta.reverse
  notify:
    - Restart Bind9
    - Reconfigure rndc 
       
- name: Enable bind9
  service:
    name: bind9
    state: started
    enabled: true
      
      
        