
- name: Install bind9
  apt:
    name:
      - bind9
      - python3-dnspython
      
- name: Options configuration file
  template:
    src: named.conf.options
    dest: /etc/bind/named.conf.options
  no_log: false
  notify:
    - Restart Bind9
    - Reload Rndc
  register: dns_config  
  
- name: Local
  template:
    src: named.conf.local
    dest: /etc/bind/named.conf.local
  notify:
    - Restart Bind9
    - Reload Rndc
  register: dns_config  
  
- name: DNS Master Zone
  template:
    src: db.maledet
    dest: /var/cache/bind/db.maledet
    force: no
  notify:
    - Restart Bind9
    - Reload Rndc
  when: inventory_hostname in groups ['dns_primary']
  register: dns_config  
  
- name: Resolv file
  template: 
    src: resolv.conf
    dest: /etc/resolv.conf
  notify:
    - Stop Resolved
        
- name: Enable bind9
  service:
    name: bind9
    state: started
    enabled: yes        